---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gb4-storage
  namespace: gb4
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-ssd-ms1